# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-10 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_site_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Form_Details',
        ),
    ]
