# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-10 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_site_app', '0003_auto_20200510_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='age',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='zips',
            field=models.CharField(max_length=50),
        ),
    ]
